package:
  name: libjpeg-turbo2
  version: 2.0.3
  epoch: 1
  description: "Accelerated baseline JPEG compression and decompression library"
  copyright:
    - license: BSD-3-Clause AND IJG AND Zlib

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - build-base
      - ca-certificates-bundle
      - cmake
      - nasm
      - samurai # use ninja pkg later?
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/libjpeg-turbo/libjpeg-turbo
      tag: ${{package.version}}
      expected-commit: 5db6a6819d0f904e0b58f34ae928fea234adb1a0

  - runs: |
      cmake -B build -G Ninja \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=/usr/lib \
        -DBUILD_SHARED_LIBS=True \
        -DCMAKE_BUILD_TYPE=MinSizeRel \
        -DWITH_JPEG8=1
      cmake --build build

  - runs: |
      DESTDIR="${{targets.destdir}}" cmake --install build

  - uses: strip

subpackages:
  - name: "libjpeg-turbo2-dev"
    description: "headers for libjpeg-turbo2"
    pipeline:
      - uses: split/dev

  - name: "libjpeg-turbo2-doc"
    description: "libjpeg-turbo2 documentation"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share/doc/libjpeg-turbo
          mv doc/* "${{targets.subpkgdir}}"/usr/share/doc/libjpeg-turbo
    dependencies:
      runtime:
        - libjpeg-turbo-dev

  - name: "libjpeg-turbo2-utils"
    description: "Utilities for manipulating JPEG images"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/* "${{targets.subpkgdir}}"/usr/bin

