package:
  name: poppler
  version: 24.05.0
  epoch: 0
  description: "poppler"
  copyright:
    - license: GNU General Public License v2.0 or later

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - wolfi-base
      - build-base
      - freetype-dev
      - fontconfig-dev
      - libnss-dev
      - libnspr-dev
      - tiff-dev
      - glib-dev
      - glib-gir
      - zlib-dev
      - openjpeg-dev
      - openjpeg-tools
      - lcms2-dev
      - cairo-dev
      - xkbcomp-dev
      - gtk-3-dev
      - gobject-introspection-dev
      - pango-dev
      - expat-dev
      - cmake
      - gcc
      - ninja
      - boost-dev

pipeline:
  - uses: fetch
    with:
      uri: https://gitlab.freedesktop.org/poppler/poppler/-/archive/poppler-${{package.version}}/poppler-poppler-${{package.version}}.tar.gz
      expected-sha256: 72dbd8bddb719bfe0abd41250909f9552bca82ab43a4ae547d2cc24159062590

  - runs: |
      cmake -B build -G Ninja . \
      -DBUILD_CPP_TESTS="OFF" \
      -DBUILD_GTK_TESTS="OFF" \
      -DBUILD_MANUAL_TESTS="OFF" \
      -DBUILD_QT5_TESTS="OFF" \
      -DBUILD_QT6_TESTS="OFF" \
      -DCMAKE_BUILD_TYPE=RelWithDebInfo \
      -DCMAKE_INSTALL_LIBDIR=lib \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DCMAKE_SYSTEM_NAME=Linux \
      -DCMAKE_HOST_SYSTEM_NAME=Linux \
      -DENABLE_BOOST=ON \
      -DENABLE_GPGME=OFF \
      -DENABLE_LIBCURL=OFF \
      -DENABLE_QT5=OFF \
      -DENABLE_QT6=OFF \
      -DENABLE_UNSTABLE_API_ABI_HEADERS=ON \
      -DCMAKE_BUILD_WITH_INSTALL_RPATH=TRUE \
      -DCMAKE_INSTALL_RPATH=/usr/bin

  - runs: |
      cmake --build build     

  - runs: |
      DESTDIR="${{targets.destdir}}" cmake --install build

  - uses: strip