package:
  name: tesseract52
  version: 5.2.0
  epoch: 2
  description: Tesseract Open Source OCR Engine (5.2.0)
  copyright:
    - license: Apache-2.0

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - cairo-dev
      - cmake
      - curl-dev
      - expat-dev
      - fontconfig-config
      - fontconfig-dev
      - fribidi-dev
      - glib-dev
      - harfbuzz-dev
      - icu-dev
      - leptonica-dev
      - libarchive-dev
      - libfontconfig1
      - libjpeg-turbo-dev
      - libxft-dev
      - opencl-dev
      - pango
      - pango-dev
      - pkgconf
      - pkgconf-dev

data:
  - name: langs
    items:
      afr:
      ara:
      aze:
      bel:
      ben:
      bul:
      cat:
      ces:
      chi_sim:
      chi_tra:
      chr:
      dan:
      deu:
      eng:
      enm:
      epo:
      equ:
      est:
      eus:
      fin:
      fra:
      frk:
      frm:
      glg:
      grc:
      heb:
      hin:
      hrv:
      hun:
      ind:
      isl:
      ita:
      ita_old:
      jpn:
      kan:
      kat:
      khm:
      kor:
      lav:
      lit:
      mal:
      mkd:
      mlt:
      msa:
      nld:
      nor:
      osd:
      pol:
      por:
      ron:
      rus:
      slk:
      slv:
      spa:
      spa_old:
      sqi:
      srp:
      swa:
      swe:
      tam:
      tel:
      tgl:
      tha:
      tur:
      ukr:
      vie:

vars:
  tessdata-version: 4.1.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/tesseract-ocr/tesseract
      tag: ${{package.version}}
      expected-commit: 5ad5325a0aa8effc47ca033625b6a51682f82767

  # Training data is stored in a separate repository
  - uses: git-checkout
    with:
      repository: https://github.com/tesseract-ocr/tessdata
      destination: tessdata-${{vars.tessdata-version}}
      tag: ${{vars.tessdata-version}}
      expected-commit: 4767ea922bcc460e70b87b1d303ebdfed0897da8

  - runs: |
      # They have some hardcoded include paths
      ln -s /usr/include/pango-1.0 /usr/include/pango

  - uses: cmake/configure
    with:
      opts: -DTESSDATA_PREFIX=/usr/share -DUSE_SYSTEM_ICU=on

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: tesseract52-dev
    pipeline:
      - uses: split/dev

  - range: langs
    name: tesseract52-${{range.key}}
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/share/tessdata
          mv tessdata-${{vars.tessdata-version}}/${{range.key}}.traineddata ${{targets.subpkgdir}}/usr/share/tessdata/
